# Generated by Django 6.0.7 on 2026-08-14 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=250)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        help_text="e.g. '2024 - Present' or 'Education'", max_length=100
                    ),
                ),
                ("role", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                (
                    "location",
                    models.CharField(default="Dhaka, Bangladesh", max_length=150),
                ),
                ("description", models.TextField()),
                (
                    "highlights",
                    models.TextField(
                        blank=True, help_text="Newline-separated bullet achievements"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Abdullah Al Noman", max_length=200)),
                (
                    "title",
                    models.CharField(
                        default="AI & Machine Learning Specialist | Full-Stack Engineer",
                        max_length=250,
                    ),
                ),
                (
                    "bio_quote",
                    models.CharField(
                        default="My style is not just about what I wear, it's about how I live.",
                        max_length=300,
                    ),
                ),
                ("about_text", models.TextField()),
                (
                    "location",
                    models.CharField(default="Dhaka, Bangladesh", max_length=200),
                ),
                (
                    "email",
                    models.EmailField(
                        default="nomanabdullah04@gmail.com", max_length=254
                    ),
                ),
                (
                    "github_url",
                    models.URLField(default="https://github.com/nomanabdullah04"),
                ),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                (
                    "avatar_url",
                    models.URLField(
                        default="https://avatars.githubusercontent.com/u/170800597?v=4"
                    ),
                ),
                (
                    "resume_file",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AI & Deep Learning", "AI & Deep Learning"),
                            ("Full-Stack Web", "Full-Stack Web"),
                            ("MLOps & Data", "MLOps & Data"),
                            ("Cyber Security", "Cyber Security"),
                        ],
                        default="AI & Deep Learning",
                        max_length=100,
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Production Live App', 'Neural Networks'",
                        max_length=100,
                    ),
                ),
                ("summary", models.TextField(help_text="Short card summary")),
                (
                    "description",
                    models.TextField(help_text="Full detailed modal description"),
                ),
                (
                    "image_url",
                    models.URLField(
                        default="https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        help_text="Comma-separated tags (e.g. Python, PyTorch, React)",
                        max_length=300,
                    ),
                ),
                ("live_url", models.URLField(blank=True, null=True)),
                (
                    "github_url",
                    models.URLField(default="https://github.com/nomanabdullah04"),
                ),
                (
                    "metrics",
                    models.CharField(
                        blank=True, help_text="e.g. '98.5% Accuracy'", max_length=200
                    ),
                ),
                ("featured", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.CharField(blank=True, max_length=250)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Skill Categories",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.IntegerField(
                        default=85, help_text="Proficiency percentage (0-100)"
                    ),
                ),
                ("icon", models.CharField(default="Code2", max_length=50)),
                ("is_featured", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="api.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-level", "name"],
            },
        ),
    ]
