# Generated by Django 6.0.7 on 2026-08-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, default="+880 1700-000000", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="whatsapp",
            field=models.CharField(
                blank=True, default="+880 1700-000000", max_length=50
            ),
        ),
    ]
