# Generated by Django 6.0.7 on 2026-08-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_contactmessage_phone_profile_phone_profile_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                default="https://www.instagram.com/nom_an041?igsh=YXE1eDlmajdpZWJj",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_url",
            field=models.URLField(default="/noman_profile.png"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio_quote",
            field=models.CharField(
                default="There is no data like more data.", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                default="abdullahcse.cou14@gmail.com", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin_url",
            field=models.URLField(
                blank=True,
                default="https://www.linkedin.com/in/abdullah-al-noman-0540402a8",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, default="+880 1307-886773", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="whatsapp",
            field=models.CharField(blank=True, default="+8801307886773", max_length=50),
        ),
    ]
